### ISSUE TITLE
[要望]画像生成後に LGTN と LGTM を切り替えられるようにしてほしい

### ISSUE THREAD

**Issue by lobin-z0x50** [haruyan-hopemucci/lgtn#21]
画像生成後、LGTN と LGTM を切り替えられるようにしてほしい。

画像生成後、クリップボードに生成後の画像が入っているので、再度ペーストすると、文字の部分の `N` と `M` の部分が重なってしまう。

あと、本要望とは直接関係ないかもしれないが、LGTN と LGTM を切り替えようとして何度もペースト操作をしていると、
画像の重ね合わせになっているのか、色が濃くなっていく。
`Ctrl + v` 連打をすると、すぐに再現できた。
`N` と `M` の部分が重なってしまうのは理解できるが、色が濃くなるのはなぜだろう。
他の画像を改めてコピー＆ペーストすると、キャンバスがクリアされたのか、画像が重なることはなく期待通りに動作した。

https://github.com/haruyan-hopemucci/lgtn/assets/11419109/ff4f1b76-85bd-4250-a160-8013f1d54991

**Comment by haruyan-hopemucci** [comment]
要望ありがとうございます😄

> 画像生成後、LGTN と LGTM を切り替えられるようにしてほしい。

対応しました。画像生成後にLGTNとLGTMをラジオボタンで切り替えられます。切り替えると画像が選択した側のテキストで再生成されクリップボードにコピーされます。

> LGTN と LGTM を切り替えようとして何度もペースト操作をしていると、画像の重ね合わせになっているのか、色が濃くなっていく。

調査の結果、`canvas`の画像をコピー際、またはコピーした画像を再度ペーストする際に、モニタのカラープロファイルによって画像データに色の補正がかかるようだということがわかりました。
今の所MacOS Ventureでのみ発生を確認しています。Windows10では発生しませんでした。
この件はOS側の挙動によるものであり、アプリ側としては仕様ということでご理解いただければと思います。
